name: Create Bot PR
on:
  push:
    branches:
      - develop
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "Merge develop into main" --body "Automated PR created by GitHub Actions to merge develop into main." --base main --head develop || true
